application:
  display-name: ${NOTIFICATION_MS_DISPLAY_NAME:mcw-notification-ms}
  server:
    port: ${NOTIFICATION_MS_SERVER_PORT::8090}
  smtp:
    from: tahirqasimov016@gmail.com
    password: rvpx szjl njar mzfz
    host: smtp.gmail.com
    port: 587
  twilio:
    sid:
    token:
    from: