application:
  display-name: ${USER_MANAGEMENT_MS_DISPLAY_NAME:mcw-user-management-ms}
  server:
    context-path: ${USER_MANAGEMENT_MS_SERVER_CONTEXT_PATH:/authz}
    api-version: ${USER_MANAGEMENT_MS_SERVER_API_VERSION:v1}
    port: ${USER_MANAGEMENT_MS_SERVER_PORT::8089}
  datasource:
    primary-url: sqlserver://${DB_CONNECTION_USERNAME:sa}:${DB_CONNECTION_PASSWORD:StrongPassword123!}@${PRIMARY_DB_HOST:localhost}:${PRIMARY_DB_PORT:5434}?database=${USER_MANAGEMENT_MS_DB_NAME:mcw.user_management_ms}
    secondary-url: sqlserver://${DB_CONNECTION_USERNAME:sa}:${DB_CONNECTION_PASSWORD:StrongPassword123!}@${SECONDARY_DB_HOST:localhost}:${SECONDARY_DB_PORT:5434}?database=${USER_MANAGEMENT_MS_DB_NAME:mcw.user_management_ms}
    max-idle-connections: ${DB_MAX_IDLE_CONNECTION:20}
    max-open-connections: ${DB_MAX_OPEN_CONNECTION:100}
    connection-max-lifetime: ${DB_CONNECTION_MAX_LIFETIME:30}
  migration: ${MIGRATIONS_URI:file://resources/db/migrations/dev}
  security:
    issuer: Mocrypt Security Issuer
    secret: ${APP_SECRET_KEY:This my secret key for Global Money Transfer Application. Please change in production !!!}
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 604800
  redis:
    address: localhost:6379
  oauth2:
    client-id: 1013075271844-af6hsi58p3gee2bdu8qcg9g6m4s6br1n.apps.googleusercontent.com
    client-secret: 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
    redirect_uri: http://localhost:8089/authz/v1/auth/google/call-back
    scope: https://www.googleapis.com/auth/userinfo.email
  webauthn:
    rp-display-name: MyApp
    rp-id: localhost
    rp-origin: http://localhost:5500